### ISSUE TITLE
The build fails if any private repository is used as a dependency

### ISSUE THREAD

**Issue by GErP83** [swiftlang/github-workflows#59]
If any private repository is used as a dependency in a project, the following error appears after running [swift_package_test.yml](https://github.com/swiftlang/github-workflows/blob/main/.github/workflows/swift_package_test.yml):

```
fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.
```
This issue can be resolved by adding this [action](https://github.com/marketplace/actions/webfactory-ssh-agent) as a new step before checkout step:

```
- name: Add keys to ssh-agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.YOUR_SECRET_HERE }}
```

I am happy to provide a PR, if that would be useful.
